---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.1
    app.quarkus.io/build-timestamp: 2025-05-02 - 12:36:05 +0000
  labels:
    app.kubernetes.io/name: devoxxuk-hello
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: devoxxuk-hello
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: devoxxuk-hello
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.1
    app.quarkus.io/build-timestamp: 2025-05-02 - 12:36:05 +0000
  labels:
    app.kubernetes.io/name: devoxxuk-hello
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: devoxxuk-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: devoxxuk-hello
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.22.1
        app.quarkus.io/build-timestamp: 2025-05-02 - 12:36:05 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: devoxxuk-hello
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GREETING
              value: "Bonjour"
          image: docker.io/sebi2706/devoxxuk-hello:1.2
          imagePullPolicy: Always
          name: devoxxuk-hello
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
